name: E2E Tests - Epic 3

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: kyros_poc
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install root dependencies
        run: npm ci

      - name: Install API dependencies
        run: |
          cd apps/api
          pip install -r requirements.txt

      - name: Seed database
        run: |
          cd apps/api
          # Run database migrations/seeds if available
          # python seed_database.py

      - name: Start API service
        run: |
          cd apps/api
          uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 10
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/kyros_poc

      - name: Health check API
        run: |
          curl --retry 5 --retry-delay 2 http://localhost:8000/health

      - name: Install Shell UI dependencies
        run: |
          cd apps/shell-ui
          npm ci

      - name: Install Playwright Browsers
        run: |
          cd apps/shell-ui
          npx playwright install --with-deps chromium

      - name: Run E2E tests
        run: |
          cd apps/shell-ui
          npm run test:e2e:chromium
        env:
          BASE_URL: http://localhost:3000

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: apps/shell-ui/playwright-report/
          retention-days: 30

      - name: Upload test videos
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-videos
          path: apps/shell-ui/test-results/
          retention-days: 7
